### ISSUE TITLE
Error console Shulker place

### ISSUE THREAD

**Issue by Heriptik** [Luohuayu/CatServer#231] opened 2020-07-14 23:45 UTC
Hi, i use CatServer-1.12.2-fb72736 and i have this error in console when i place Shulker boxe : [https://paste.ubuntu.com/p/4b4M96zrkW/](https://paste.ubuntu.com/p/4b4M96zrkW/)

**Comment by Heriptik** [comment] 2020-07-15 01:29
And this error : [https://paste.ubuntu.com/p/NmC3Fs2Trx/](https://paste.ubuntu.com/p/NmC3Fs2Trx/)

There really must be a mistake with the shulkerbox

Other Gcore plugin error : [https://paste.ubuntu.com/p/v3PbfM3Fhc/](https://paste.ubuntu.com/p/v3PbfM3Fhc/) But it still works

**Comment by Luohuayu** [comment] 2020-07-19 01:30
Please upload debug.log

**Comment by Heriptik** [comment] 2020-07-19 01:39
Debug.log : https://drive.google.com/file/d/14wRWEsoDwRPlkDA0DovSeWzQ7hDL3dfB/view?usp=sharing

**Comment by Luohuayu** [comment] 2020-07-20 07:00
duplicate of #233

**Closed as completed by Luohuayu** 2020-07-20 07:00 UTC
Labels: question
