### ISSUE TITLE
[1.16.5] PlayerDeathEvent.setKeepInventory(true) not working

### ISSUE THREAD

**Issue by Serega007RU** [Luohuayu/CatServer#486] opened 2022-06-17 06:50 UTC
**Environment**

Minecraft version(1.12.2/1.16.5/1.18.2): 1.16.5
Build version(Get from /version command): 1.16.5-589d8617
Mods/Plugins: SaveInv

**Describe the bug**
(If there is an error, please attach the pastebin link)
When using the PlayerDeathEvent.setKeepInventory(true) method, the player's inventory is not saved

**Expected behavior**
The player's inventory must be preserved

**To Reproduce**
Install the SaveInv plugin, give yourself an OP, die. He will write in the chat that your inventory is saved, but in fact it is not saved
[SaveInv.zip](https://github.com/Luohuayu/CatServer/files/8925189/SaveInv.zip)

**Screenshot/Video**
(If it doesn't exist you can ignore it)

**Comment by Kotori0629** [comment] 2022-06-17 07:11
Duplicate of #454

**Closed as completed by Kotori0629** 2022-06-17 07:11 UTC
Labels: duplicate
