### ISSUE TITLE
[1.18.2] Structure generation is not working correctly (IDAS mod)

### ISSUE THREAD

**Issue by MrJorman** [Luohuayu/CatServer#559] opened 2022-08-15 19:51 UTC
**Environment**

Minecraft version(1.12.2/1.16.5/1.18.2): 1.18.2
Build version(Get from /version command): 14 build
Mods/Plugins: https://drive.google.com/file/d/1thOI5zyugkiT9l0_i96ikVKJCBuz3IRW/view?usp=sharing + lootr mod

**Describe the bug**
(If there is an error, please attach the pastebin link)

**Expected behavior**

**To Reproduce**

This is how the generation of the dungeon in the IDAS mod should look like /locate idas:abandonhouse
![image](https://user-images.githubusercontent.com/55187962/184707318-d3967bde-6aa1-41a4-9838-7e51ef73179f.png)

On the server it looks like this:
![image](https://user-images.githubusercontent.com/55187962/184707349-fa3a9d43-1d69-4161-9d86-5e3487c1b40e.png)
![image](https://user-images.githubusercontent.com/55187962/184707363-3020107e-f1d8-46d7-9012-617f0cef11da.png)

All blocks are mixed up, the structure is not generated correctly.

**Screenshot/Video**
(If it doesn't exist you can ignore
[latest.log](https://github.com/Luohuayu/CatServer/files/9339502/latest.log)
 it)

**Comment by Kotori0629** [comment] 2022-08-15 19:59
I will rest first, I will try to solve this problem tomorrow

**Comment by MrJorman** [comment] 2022-08-16 17:19
fixed?

**Comment by XionioXMaster** [comment] 2022-08-17 12:01
> I will rest first, I will try to solve this problem tomorrow
https://youtu.be/GEinR1Y462M

**Comment by XionioXMaster** [comment] 2022-08-17 12:13
> I will rest first, I will try to solve this problem tomorrow

The server started me without one mod

It doesn't seem to send the player a warning about a missing mod.

In turn, the Magma server was unable to reproduce me without the right mod

**Comment by Kotori0629** [comment] 2022-08-17 12:15
> > I will rest first, I will try to solve this problem tomorrow
> 
> The server started me without one mod
> 
> It doesn't seem to send the player a warning about a missing mod.
> 
> In turn, the Magma server was unable to reproduce me without the right mod

Magma's Forge version? Try use same version ForgeServer

**Comment by XionioXMaster** [comment] 2022-08-17 12:21
> > > I will rest first, I will try to solve this problem tomorrow
> > 
> > 
> > The server started me without one mod
> > It doesn't seem to send the player a warning about a missing mod.
> > In turn, the Magma server was unable to reproduce me without the right mod
> 
> Magma's Forge version? Try use same version ForgeServer

Magma 1.18.2
Version: 9997ace2

using it I have no problems with loading chunks and unidentified blocks from my video

**Comment by JotaroJudso** [comment] 2022-09-11 20:59
У меня такая же проблема в любом моде который добавляет новые блоки

**Comment by Kotori0629** [comment] 2023-03-03 12:55
fixed in the remake

**Closed as completed by Kotori0629** 2023-03-03 12:55 UTC
Labels: bug, beta
