### ISSUE TITLE
bukkit message to many

### ISSUE THREAD

**Issue by minjae9010** [Luohuayu/CatServer#293] opened 2020-12-24 14:24 UTC
[23:24:19] [pool-33-thread-1/WARN]: Please check the stacktrace in debug.log and report the author.
[23:24:19] [pool-33-thread-1/WARN]: A Mod/Plugin try to async open gui, it will be executed safely on the main server thread until return!

why many log to bukkit...

[debug.log](https://github.com/Luohuayu/CatServer/files/5739869/debug.log)

**Comment by Luohuayu** [comment] 2020-12-24 15:05
Duplicate of #276
Please wait for CustomNPCs update

**Closed as completed by Luohuayu** 2020-12-24 15:05 UTC
