### ISSUE TITLE
[1.16.5] World guard

### ISSUE THREAD

**Issue by SqdGoodlol** [Luohuayu/CatServer#633] opened 2022-10-04 09:27 UTC
**Environment**

Minecraft version(1.12.2/1.16.5/1.18.2): 1.16.5
Build version(Get from /version command): 1.16.5-105db771
Mods/Plugins:  worldguard-bukkit-7.0.5-dist

**Describe the bug**
The pvp ban flag does not work

**Expected behavior**

**To Reproduce**

**Screenshot/Video**
![image](https://user-images.githubusercontent.com/86075284/193784521-58eca13f-658c-4f64-9ea6-e1b0835f8f48.png)
![image](https://user-images.githubusercontent.com/86075284/193784596-a081c264-e91a-451a-bcdb-254b1c7cd443.png)
![image](https://user-images.githubusercontent.com/86075284/193784661-c2d9d3bc-da7f-49fa-9cfc-809721f82f92.png)
![image](https://user-images.githubusercontent.com/86075284/193784773-33572fbd-bbdc-42a9-950d-bf482cd70c88.png)

**Comment by SqdGoodlol** [comment] 2022-10-04 09:27
![image](https://user-images.githubusercontent.com/86075284/193784842-11d2806a-c3f8-4be0-9a57-07dcaafacfde.png)

**Comment by MrJorman** [comment] 2022-10-05 09:11
https://github.com/Luohuayu/CatServer/issues/548 this problem. need fix!

**Comment by Kotori0629** [comment] 2022-10-06 05:06
Duplicate of #548

**Closed as completed by Kotori0629** 2022-10-06 05:06 UTC
Labels: duplicate
