### ISSUE TITLE
Skins dont work.

### ISSUE THREAD

**Issue by Zilacon** [Luohuayu/CatServer#375] opened 2021-11-08 10:06 UTC
Hello, i switched from Mohist to CatServer due to them refusing to fix the mountain of problems with it.
But mohist didnt have an issue with skins, while CatServer seems to be a lot more stable, no one can see anyones skins.

Could this be fixed? This is an issue on 8 different servers/modpacks. And switching to Mohist shows player skins, so its just an issue with CatServer.

Thanks.

**Comment by Luohuayu** [comment] 2021-11-08 20:08
Are you using online mode or a skin plugn?

**Comment by Zilacon** [comment] 2021-11-08 20:10
> Are you using online mode or a skin plugn?

The servers are in offline mode, so they can be used with bungeecord, which is in online mode.
I am not using any skin plugins.

**Comment by Luohuayu** [comment] 2021-11-08 21:02
Which version of BungeeCord are you using?

**Comment by Zilacon** [comment] 2021-11-08 21:04
> Which version of BungeeCord are you using?

Its custom, but we keep up with the official bungeecord, waterfall, and flamecord with patches.

**Comment by Luohuayu** [comment] 2021-11-08 21:25
I can’t reproduce it on normal BungeeCord

**Comment by Fox2Code** [comment] 2021-11-09 19:51
Hi, I'm the maintainer and main developer of the custom BungeeCord that APOC use, the custom Bungee use a system to fix invalid packets in real time to fix issues such as skin not working or client crashes.

Somehow CatServer is sending unsigned skin data, causing skin to be invalid client side.

Due to clients using their own skin data from their local profile as fallback **this make the issue impossible to detect without being at least 2 players on the same server**, and trying to check the other player skin.

The packet fixer was able to fix skin data being invalid only with theses changes:
```diff
-                        if (item.getProperties() == null || item.getProperties().length == 0) {
+                        if (item.getProperties() == null || item.getProperties().length == 0 ||
+                                item.getProperties()[0].length < 3 || connection.isForceSkinRewrite()) {
```
Note: `isForceSkinRewrite` return `false`, so the most important part in the fix is `item.getProperties()[0].length < 3`

A normal property is supposed to be `new String[]{"key", "value", "signature"}`, but somehow CatServer isn't sending the signature, triggering the fix of the packet and resolving the skin issue on our BungeeCord, but an unmodified BungeeCord don't have such mechanism to fix invalid tab packet send to them. (Skin is managed by the tab list in `1.12.2`)

While we have fixed the issue on the BungeeCord side, I asked @Zilacon to leave this issue open to help CatServer fix the skin issue on all modded servers, and not only the one using our specific packet fixer.

**Comment by Luohuayu** [comment] 2021-11-10 09:52
@Fox2Code Skin data is signed
![1](https://user-images.githubusercontent.com/29095770/141089812-091f80fe-3be9-4df6-adae-8593417678c5.png)

**Comment by Fox2Code** [comment] 2021-11-10 14:51
Well, probably due to an edge case the data is not signed, the workaround on Gateway (name of the custom BungeeCord) work well enough for now.

**Closed as completed** 2022-04-15 13:10 UTC
